default_context:
  project_name: 'track'
  project_slug: 'track'
  domain_main: 'track.in'
  secret_key: '98c276df2089d0312ab43a6c18cbc94437b884edfb0b2e2553ebbb9f65c80251'
  first_superuser: 'admin@track.in'
  first_superuser_password: 'ticket321$'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.ticket.com", "https://stag.ticket.com", "https://ticket.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@track.in'
  postgres_password: 'postgres'
  pgadmin_default_user: 'postgres'
  pgadmin_default_user_password: 'postgres'
  traefik_constraint_tag: 'traefik-ticket.com'
  traefik_constraint_tag_staging: 'stag.traefik-ticket.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:ticket321$'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
