version: "3.6"

services:
  backend:
    environment:
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
      - SERVER_HOST=http://${DOMAIN}
      - SEED_DATA=${SEED_DATA}
      - REFRESH_SCHEMA=${REFRESH_SCHEMA}
      - LOG_LEVEL=debug
      
