version: '3.6'
services:
  db:
    env_file:
      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    env_file:
      - env-postgres.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - SEED_DATA=${SEED_DATA}
      - REFRESH_SCHEMA=${REFRESH_SCHEMA}
